upgrade kad-dht version to v0.2.1
lower kad-dht  version depends on "golang.org/x/xerrors v0.0.0-20190513163551-3ee3066db522",which when build binarytarget makes deps mistake "/x/xerrors@v0.0.0-20190513163551-3ee3066db522/adaptor_go1_13.go:16:14: undefined: errors.Frame ","/x/xerrors@v0.0.0-20190513163551-3ee3066db522/format_go1_13.go:12:18: undefined: errors.Formatter"